In [6]:
import pandas as pd

stops = pd.read_csv("../data/static/stops.txt")
trips = pd.read_csv("../data/static/trips.txt")
stop_times = pd.read_csv("../data/static/stop_times.txt")
routes = pd.read_csv("../data/static/routes.txt")

print("Data loaded successfully!")
print("Stops:", stops.shape)
print("Trips:", trips.shape)
print("Stop times:", stop_times.shape)

Data loaded successfully!
Stops: (625, 9)
Trips: (11479, 9)
Stop times: (153477, 9)

In [3]:
print("STOPS")
display(stops.head())

print("\nTRIPS")
display(trips.head())

print("\nSTOP TIMES")
display(stop_times.head())

STOPS

,stop_id,stop_name,stop_lat,stop_lon,stop_url,location_type,parent_station,wheelchair_boarding,level_id
0,11212,Flinders Street Station,-37.818095,144.966266,https://transport.vic.gov.au/stop/1071/?utm_so...,NaN,vic:rail:FSS,1.0,Level 0
1,11213,Flinders Street Station,-37.818144,144.966492,https://transport.vic.gov.au/stop/1071/?utm_so...,NaN,vic:rail:FSS,1.0,Level 0
2,11214,Flinders Street Station,-37.818198,144.966524,https://transport.vic.gov.au/stop/1071/?utm_so...,NaN,vic:rail:FSS,1.0,Level 0
3,11215,Flinders Street Station,-37.818289,144.966556,https://transport.vic.gov.au/stop/1071/?utm_so...,NaN,vic:rail:FSS,1.0,Level 0
4,11216,Flinders Street Station,-37.818326,144.966600,https://transport.vic.gov.au/stop/1071/?utm_so...,NaN,vic:rail:FSS,1.0,Level 0

TRIPS

,route_id,service_id,trip_id,shape_id,trip_headsign,direction_id,block_id,wheelchair_accessible,bikes_allowed
0,aus:vic:vic-01-ABY:,T3_1,01-ABY--10-T3-8605,1-ABY-mjp-10.1.H,Albury,0,NaN,1,1
1,aus:vic:vic-01-ABY:,T3_1,01-ABY--10-T3-8610,1-ABY-mjp-10.2.R,Southern Cross,1,NaN,1,1
2,aus:vic:vic-01-ABY:,T3_1,01-ABY--10-T3-8615,1-ABY-mjp-10.1.H,Albury,0,NaN,1,1
3,aus:vic:vic-01-ABY:,T3_1,01-ABY--10-T3-8617,1-ABY-mjp-10.1.H,Albury,0,NaN,1,1
4,aus:vic:vic-01-ABY:,T3_1,01-ABY--10-T3-8620,1-ABY-mjp-10.2.R,Southern Cross,1,NaN,1,1

STOP TIMES

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled
0,01-ABY--10-T3-8605,07:07:00,07:07:00,20043,1,NaN,0,0,0.00
1,01-ABY--10-T3-8605,07:35:00,07:35:00,22254,2,NaN,0,1,27298.68
2,01-ABY--10-T3-8605,08:24:00,08:26:00,20342,3,NaN,0,0,109304.76
3,01-ABY--10-T3-8605,08:37:00,08:37:00,20289,4,NaN,0,0,126589.63
4,01-ABY--10-T3-8605,08:56:00,08:56:00,20312,5,NaN,0,0,187114.84

In [4]:
print("Missing values in Stops:")
print(stops.isnull().sum())

print("\nMissing values in Trips:")
print(trips.isnull().sum())

print("\nMissing values in Stop Times:")
print(stop_times.isnull().sum())

Missing values in Stops:
stop_id                  0
stop_name                0
stop_lat                 0
stop_lon                 0
stop_url               414
location_type          211
parent_station         110
wheelchair_boarding    204
level_id               111
dtype: int64

Missing values in Trips:
route_id                     0
service_id                   0
trip_id                      0
shape_id                     0
trip_headsign                0
direction_id                 0
block_id                 11479
wheelchair_accessible        0
bikes_allowed                0
dtype: int64

Missing values in Stop Times:
trip_id                     0
arrival_time                0
departure_time              0
stop_id                     0
stop_sequence               0
stop_headsign          153477
pickup_type                 0
drop_off_type               0
shape_dist_traveled         0
dtype: int64

In [5]:
print("Number of routes:", routes.shape[0])
print("\nRoute details:")
display(routes)

NameError: name 'routes' is not defined

In [7]:
print("Number of routes:", routes.shape[0])
print("\nRoute details:")
display(routes)

Number of routes: 13

Route details:

,route_id,agency_id,route_short_name,route_long_name,route_type,route_color,route_text_color
0,aus:vic:vic-01-ABY:,NaN,Seymour,Albury - Melbourne Via Seymour,2,8F1A95,FFFFFF
1,aus:vic:vic-01-ART:,NaN,Ballarat,Ararat - Melbourne Via Ballarat,2,8F1A95,FFFFFF
2,aus:vic:vic-01-BAT:,NaN,Ballarat,Ballarat - Melbourne Via Melton,2,8F1A95,FFFFFF
3,aus:vic:vic-01-BDE:,NaN,Traralgon,Bairnsdale - Melbourne Via Traralgon & Sale,2,8F1A95,FFFFFF
4,aus:vic:vic-01-BGO:,NaN,Bendigo,Bendigo - Melbourne Via Sunbury,2,8F1A95,FFFFFF
5,aus:vic:vic-01-ECH:,NaN,Bendigo,Echuca/Moama - Melbourne Via Bendigo or Heathcote,2,8F1A95,FFFFFF
6,aus:vic:vic-01-GEL:,NaN,Geelong,Geelong - Melbourne Via Geelong,2,8F1A95,FFFFFF
7,aus:vic:vic-01-MBY:,NaN,Ballarat,Maryborough - Melbourne Via Ballarat,2,8F1A95,FFFFFF
8,aus:vic:vic-01-SER:,NaN,Seymour,Seymour - Melbourne Via Broadmeadows,2,8F1A95,FFFFFF
9,aus:vic:vic-01-SNH:,NaN,Seymour,Shepparton - Melbourne Via Seymour,2,8F1A95,FFFFFF
10,aus:vic:vic-01-SWL:,NaN,Bendigo,Swan Hill - Melbourne Via Bendigo,2,8F1A95,FFFFFF
11,aus:vic:vic-01-TRN:,NaN,Traralgon,"Traralgon - Melbourne Via Pakenham, Moe & Morwell",2,8F1A95,FFFFFF
12,aus:vic:vic-01-WBL:,NaN,Geelong,Warrnambool - Melbourne Via Geelong & Colac,2,8F1A95,FFFFFF

In [8]:
print("Route types:")
print(routes["route_type"].value_counts())

Route types:
route_type
2    13
Name: count, dtype: int64

In [9]:
print("Route names:")
print(routes[["route_short_name", "route_long_name"]])

Route names:
   route_short_name                                    route_long_name
0           Seymour                     Albury - Melbourne Via Seymour
1          Ballarat                    Ararat - Melbourne Via Ballarat
2          Ballarat                    Ballarat - Melbourne Via Melton
3         Traralgon        Bairnsdale - Melbourne Via Traralgon & Sale
4           Bendigo                    Bendigo - Melbourne Via Sunbury
5           Bendigo  Echuca/Moama - Melbourne Via Bendigo or Heathcote
6           Geelong                    Geelong - Melbourne Via Geelong
7          Ballarat               Maryborough - Melbourne Via Ballarat
8           Seymour               Seymour - Melbourne Via Broadmeadows
9           Seymour                 Shepparton - Melbourne Via Seymour
10          Bendigo                  Swan Hill - Melbourne Via Bendigo
11        Traralgon  Traralgon - Melbourne Via Pakenham, Moe & Morwell
12          Geelong        Warrnambool - Melbourne Via Geelong & Colac

In [10]:
print("Number of trips by route:")
print(trips["route_id"].value_counts().head(10))

Number of trips by route:
route_id
aus:vic:vic-01-GEL:    3722
aus:vic:vic-01-BAT:    2290
aus:vic:vic-01-TRN:    1546
aus:vic:vic-01-BGO:    1132
aus:vic:vic-01-SER:     760
aus:vic:vic-01-SNH:     400
aus:vic:vic-01-WBL:     350
aus:vic:vic-01-ART:     350
aus:vic:vic-01-ECH:     228
aus:vic:vic-01-ABY:     211
Name: count, dtype: int64

In [11]:
route_trip_counts = trips["route_id"].value_counts().reset_index()

route_trip_counts.columns = ["route_id", "trip_count"]

route_summary = routes.merge(
    route_trip_counts,
    on="route_id",
    how="left"
)

print("Routes with trip counts:")
display(route_summary[["route_short_name", "route_long_name", "trip_count"]])

Routes with trip counts:

,route_short_name,route_long_name,trip_count
0,Seymour,Albury - Melbourne Via Seymour,211
1,Ballarat,Ararat - Melbourne Via Ballarat,350
2,Ballarat,Ballarat - Melbourne Via Melton,2290
3,Traralgon,Bairnsdale - Melbourne Via Traralgon & Sale,210
4,Bendigo,Bendigo - Melbourne Via Sunbury,1132
5,Bendigo,Echuca/Moama - Melbourne Via Bendigo or Heathcote,228
6,Geelong,Geelong - Melbourne Via Geelong,3722
7,Ballarat,Maryborough - Melbourne Via Ballarat,140
8,Seymour,Seymour - Melbourne Via Broadmeadows,760
9,Seymour,Shepparton - Melbourne Via Seymour,400
10,Bendigo,Swan Hill - Melbourne Via Bendigo,140
11,Traralgon,"Traralgon - Melbourne Via Pakenham, Moe & Morwell",1546
12,Geelong,Warrnambool - Melbourne Via Geelong & Colac,350

In [12]:
print("Number of stops:", len(stops))

print("\nSample stops:")
display(stops[["stop_id", "stop_name", "stop_lat", "stop_lon"]].head(10))

Number of stops: 625

Sample stops:

  stop_id                stop_name   stop_lat    stop_lon
0   11212  Flinders Street Station -37.818095  144.966266
1   11213  Flinders Street Station -37.818144  144.966492
2   11214  Flinders Street Station -37.818198  144.966524
3   11215  Flinders Street Station -37.818289  144.966556
4   11216  Flinders Street Station -37.818326  144.966600
5   11217  Flinders Street Station -37.818435  144.966643
6   11218  Flinders Street Station -37.818507  144.966675
7   12172         Pakenham Station -38.080515  145.485686
8   12173         Pakenham Station -38.080434  145.485733
9   12178          Berwick Station -38.039831  145.345033

In [13]:
print("Wheelchair accessibility:")
print(stops["wheelchair_boarding"].value_counts(dropna=False))

print("\nLocation types:")
print(stops["location_type"].value_counts(dropna=False))

Wheelchair accessibility:
wheelchair_boarding
1.0    419
NaN    204
2.0      2
Name: count, dtype: int64

Location types:
location_type
NaN    211
3.0    204
1.0    110
2.0    100
Name: count, dtype: int64

In [14]:
print("Stop times sample:")
display(stop_times.head(10))

print("\nNumber of unique trips:", stop_times["trip_id"].nunique())

print("Number of unique stops:", stop_times["stop_id"].nunique())

Stop times sample:

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled
0,01-ABY--10-T3-8605,07:07:00,07:07:00,20043,1,NaN,0,0,0.00
1,01-ABY--10-T3-8605,07:35:00,07:35:00,22254,2,NaN,0,1,27298.68
2,01-ABY--10-T3-8605,08:24:00,08:26:00,20342,3,NaN,0,0,109304.76
3,01-ABY--10-T3-8605,08:37:00,08:37:00,20289,4,NaN,0,0,126589.63
4,01-ABY--10-T3-8605,08:56:00,08:56:00,20312,5,NaN,0,0,187114.84
5,01-ABY--10-T3-8605,09:07:00,09:07:00,20353,6,NaN,0,0,205308.06
6,01-ABY--10-T3-8605,09:22:00,09:24:00,20295,7,NaN,0,0,231429.77
7,01-ABY--10-T3-8605,09:47:00,09:49:00,20356,8,NaN,0,0,270158.31
8,01-ABY--10-T3-8605,10:02:00,10:02:00,22490,9,NaN,0,0,293907.04
9,01-ABY--10-T3-8605,10:10:00,10:10:00,20302,10,NaN,0,0,307692.35

Number of unique trips: 11479
Number of unique stops: 110

In [15]:
print("Number of trips by stop:")

stop_trip_counts = stop_times["stop_id"].value_counts()

display(stop_trip_counts.head(10))

Number of trips by stop:

stop_id
20043    11015
22240     8074
22241     6349
19982     5575
20314     3812
47647     3553
20334     3508
20344     3495
20321     3474
47648     3401
Name: count, dtype: int64

In [17]:
top_stops = stop_trip_counts.head(10).reset_index()
top_stops.columns = ["stop_id", "trip_count"]

top_stops["stop_id"] = top_stops["stop_id"].astype(str)
stops["stop_id"] = stops["stop_id"].astype(str)

top_stops = top_stops.merge(
    stops[["stop_id", "stop_name"]],
    on="stop_id",
    how="left"
)

display(top_stops)

  stop_id  trip_count               stop_name
0   20043       11015  Southern Cross Station
1   22240        8074       Footscray Station
2   22241        6349        Sunshine Station
3   19982        5575       Deer Park Station
4   20314        3812         Geelong Station
5   47647        3553    Wyndham Vale Station
6   20334        3508   North Geelong Station
7   20344        3495   South Geelong Station
8   20321        3474            Lara Station
9   47648        3401         Tarneit Station

In [18]:
print("Stop sequence statistics:")

print(stop_times["stop_sequence"].describe())

Stop sequence statistics:
count    153477.000000
mean          7.662158
std           4.576368
min           1.000000
25%           4.000000
50%           7.000000
75%          11.000000
max          23.000000
Name: stop_sequence, dtype: float64

In [19]:
trip_stop_counts = stop_times.groupby("trip_id")["stop_id"].count()

print("Stops per trip:")
print(trip_stop_counts.describe())

Stops per trip:
count    11479.000000
mean        13.370241
std          3.571739
min          2.000000
25%         12.000000
50%         13.000000
75%         15.000000
max         23.000000
Name: stop_id, dtype: float64

In [20]:
# Calculate trip duration

trip_times = stop_times.groupby("trip_id").agg(
    start_time=("departure_time", "min"),
    end_time=("arrival_time", "max")
)

print("Sample trip times:")
display(trip_times.head())

print("\nNumber of trips:", len(trip_times))

Sample trip times:

                   start_time  end_time
trip_id
01-ABY--10-T3-8605   07:07:00  10:43:00
01-ABY--10-T3-8610   06:45:00  10:27:00
01-ABY--10-T3-8615   12:04:00  15:40:00
01-ABY--10-T3-8617   14:33:00  18:16:00
01-ABY--10-T3-8620   12:51:00  16:33:00

Number of trips: 11479

In [22]:
# Calculate trip duration in minutes

trip_times["duration_minutes"] = (
    pd.to_timedelta(trip_times["end_time"].astype(str))
    - pd.to_timedelta(trip_times["start_time"].astype(str))
).dt.total_seconds() / 60

print("Trip duration statistics:")
print(trip_times["duration_minutes"].describe())

Trip duration statistics:
count    11479.000000
mean       108.004791
std         49.503245
min          5.000000
25%         80.000000
50%         93.000000
75%        143.000000
max        286.000000
Name: duration_minutes, dtype: float64

In [23]:
# Calculate average trip duration by route

trip_route = trips[["trip_id", "route_id"]].drop_duplicates()

route_duration = trip_route.merge(
    trip_times[["duration_minutes"]],
    left_on="trip_id",
    right_index=True,
    how="left"
)

route_duration_summary = (
    route_duration.groupby("route_id")["duration_minutes"]
    .agg(["count", "mean", "min", "max"])
    .sort_values("mean", ascending=False)
)

print("Average trip duration by route:")
display(route_duration_summary)

Average trip duration by route:

                     count        mean    min    max
route_id
aus:vic:vic-01-SWL:    140  272.171429  144.0  286.0
aus:vic:vic-01-BDE:    210  235.238095  169.0  248.0
aus:vic:vic-01-ABY:    211  222.938389  216.0  265.0
aus:vic:vic-01-WBL:    350  203.680000  190.0  216.0
aus:vic:vic-01-ECH:    228  168.587719    7.0  205.0
aus:vic:vic-01-SNH:    400  154.382500  143.0  169.0
aus:vic:vic-01-ART:    350  147.077143   56.0  160.0
aus:vic:vic-01-TRN:   1546  141.305951   76.0  154.0
aus:vic:vic-01-BGO:   1132  111.804770   25.0  139.0
aus:vic:vic-01-MBY:    140   92.985714   54.0  165.0
aus:vic:vic-01-SER:    760   87.732895   80.0   99.0
aus:vic:vic-01-BAT:   2290   76.491266    5.0  108.0
aus:vic:vic-01-GEL:   3722   75.874530   35.0   85.0

In [24]:
# Add route names to the duration summary

route_duration_named = route_duration_summary.reset_index().merge(
    routes[["route_id", "route_short_name", "route_long_name"]],
    on="route_id",
    how="left"
)

route_duration_named = route_duration_named[
    ["route_id", "route_short_name", "route_long_name",
     "count", "mean", "min", "max"]
]

print("Trip duration by route:")
display(route_duration_named)

Trip duration by route:

,route_id,route_short_name,route_long_name,count,mean,min,max
0,aus:vic:vic-01-SWL:,Bendigo,Swan Hill - Melbourne Via Bendigo,140,272.171429,144.0,286.0
1,aus:vic:vic-01-BDE:,Traralgon,Bairnsdale - Melbourne Via Traralgon & Sale,210,235.238095,169.0,248.0
2,aus:vic:vic-01-ABY:,Seymour,Albury - Melbourne Via Seymour,211,222.938389,216.0,265.0
3,aus:vic:vic-01-WBL:,Geelong,Warrnambool - Melbourne Via Geelong & Colac,350,203.680000,190.0,216.0
4,aus:vic:vic-01-ECH:,Bendigo,Echuca/Moama - Melbourne Via Bendigo or Heathcote,228,168.587719,7.0,205.0
5,aus:vic:vic-01-SNH:,Seymour,Shepparton - Melbourne Via Seymour,400,154.382500,143.0,169.0
6,aus:vic:vic-01-ART:,Ballarat,Ararat - Melbourne Via Ballarat,350,147.077143,56.0,160.0
7,aus:vic:vic-01-TRN:,Traralgon,"Traralgon - Melbourne Via Pakenham, Moe & Morwell",1546,141.305951,76.0,154.0
8,aus:vic:vic-01-BGO:,Bendigo,Bendigo - Melbourne Via Sunbury,1132,111.804770,25.0,139.0
9,aus:vic:vic-01-MBY:,Ballarat,Maryborough - Melbourne Via Ballarat,140,92.985714,54.0,165.0
10,aus:vic:vic-01-SER:,Seymour,Seymour - Melbourne Via Broadmeadows,760,87.732895,80.0,99.0
11,aus:vic:vic-01-BAT:,Ballarat,Ballarat - Melbourne Via Melton,2290,76.491266,5.0,108.0
12,aus:vic:vic-01-GEL:,Geelong,Geelong - Melbourne Via Geelong,3722,75.874530,35.0,85.0

In [25]:
# Top 5 longest routes by average duration

top_5_longest = route_duration_named.sort_values(
    "mean", ascending=False
).head(5)

print("Top 5 longest routes:")
display(top_5_longest)

Top 5 longest routes:

,route_id,route_short_name,route_long_name,count,mean,min,max
0,aus:vic:vic-01-SWL:,Bendigo,Swan Hill - Melbourne Via Bendigo,140,272.171429,144.0,286.0
1,aus:vic:vic-01-BDE:,Traralgon,Bairnsdale - Melbourne Via Traralgon & Sale,210,235.238095,169.0,248.0
2,aus:vic:vic-01-ABY:,Seymour,Albury - Melbourne Via Seymour,211,222.938389,216.0,265.0
3,aus:vic:vic-01-WBL:,Geelong,Warrnambool - Melbourne Via Geelong & Colac,350,203.680000,190.0,216.0
4,aus:vic:vic-01-ECH:,Bendigo,Echuca/Moama - Melbourne Via Bendigo or Heathcote,228,168.587719,7.0,205.0

In [26]:
# Calculate travel time between consecutive stops

stop_times_sorted = stop_times.sort_values(
    ["trip_id", "stop_sequence"]
).copy()

stop_times_sorted["arrival"] = pd.to_timedelta(
    stop_times_sorted["arrival_time"].astype(str)
)

stop_times_sorted["prev_arrival"] = (
    stop_times_sorted.groupby("trip_id")["arrival"].shift(1)
)

stop_times_sorted["stop_to_stop_minutes"] = (
    stop_times_sorted["arrival"] - stop_times_sorted["prev_arrival"]
).dt.total_seconds() / 60

print("Stop-to-stop travel time statistics:")
print(stop_times_sorted["stop_to_stop_minutes"].describe())

Stop-to-stop travel time statistics:
count    141998.000000
mean          8.731017
std           6.337039
min           2.000000
25%           5.000000
50%           7.000000
75%          10.000000
max          97.000000
Name: stop_to_stop_minutes, dtype: float64

In [27]:
# Find unusually long gaps between consecutive stops

long_gaps = stop_times_sorted[
    stop_times_sorted["stop_to_stop_minutes"] > 30
].copy()

print("Number of stop-to-stop gaps above 30 minutes:",
      len(long_gaps))

display(
    long_gaps[
        ["trip_id", "stop_sequence", "arrival",
         "prev_arrival", "stop_to_stop_minutes"]
    ].sort_values(
        "stop_to_stop_minutes",
        ascending=False
    ).head(20)
)

Number of stop-to-stop gaps above 30 minutes: 1391

,trip_id,stop_sequence,arrival,prev_arrival,stop_to_stop_minutes
82,01-ABY--10-T3-8630,11,0 days 21:12:00,0 days 19:35:00,97.0
1462,01-ABY--23-T3-8630,11,0 days 21:12:00,0 days 19:35:00,97.0
2398,01-ABY--8-T0-8630,11,0 days 21:12:00,0 days 19:35:00,97.0
790,01-ABY--19-T0_WD08-8630,11,0 days 21:12:00,0 days 19:35:00,97.0
562,01-ABY--18-T0_WD08-8630,11,0 days 21:12:00,0 days 19:35:00,97.0
430,01-ABY--15-T3-8630,11,0 days 21:12:00,0 days 19:35:00,97.0
778,01-ABY--18-T3-8630,11,0 days 21:12:00,0 days 19:35:00,97.0
1702,01-ABY--25-T0_WD08-8630,11,0 days 21:12:00,0 days 19:35:00,97.0
1990,01-ABY--2-T0-8630,11,0 days 21:12:00,0 days 19:35:00,97.0
2206,01-ABY--5-T3-8630,11,0 days 21:12:00,0 days 19:35:00,97.0
1234,01-ABY--21-T3-8630,11,0 days 21:12:00,0 days 19:35:00,97.0
1078,01-ABY--20-T0-8630,11,0 days 21:12:00,0 days 19:35:00,97.0
1246,01-ABY--22-T0_WD08-8630,11,0 days 21:12:00,0 days 19:35:00,97.0
1690,01-ABY--24-T3-8630,11,0 days 21:12:00,0 days 19:35:00,97.0
1474,01-ABY--24-T0_WD08-8630,11,0 days 21:12:00,0 days 19:35:00,97.0
1918,01-ABY--25-T3-8630,11,0 days 21:12:00,0 days 19:35:00,97.0
1006,01-ABY--19-T3-8630,11,0 days 21:12:00,0 days 19:35:00,97.0
214,01-ABY--12-T0-8630,11,0 days 21:12:00,0 days 19:35:00,97.0
38702,01-BGO--13-T0-8033,3,0 days 18:13:00,0 days 17:00:00,73.0
48998,01-BGO--6-T0-8033,3,0 days 18:13:00,0 days 17:00:00,73.0

In [28]:
# Examine the distribution of stop-to-stop travel times

print("Stop-to-stop travel time distribution:")

print(
    stop_times_sorted["stop_to_stop_minutes"]
    .value_counts()
    .sort_index()
    .tail(20)
)

Stop-to-stop travel time distribution:
stop_to_stop_minutes
37.0      6
38.0     44
39.0     61
40.0    110
41.0     23
42.0     37
43.0      6
44.0     85
45.0     34
46.0     32
47.0     89
48.0     36
49.0     96
50.0    110
51.0     29
52.0      6
53.0     88
55.0      6
73.0     17
97.0     18
Name: count, dtype: int64

In [30]:
# Investigate long gaps between consecutive stops

long_gaps = stop_times_sorted[
    stop_times_sorted["stop_to_stop_minutes"] > 30
].copy()

# Create a stop_id -> stop_name mapping
stop_name_map = stops.set_index("stop_id")["stop_name"]

# Add stop names without merging
long_gaps["stop_name"] = long_gaps["stop_id"].map(stop_name_map)

# Display the longest gaps
display(
    long_gaps[
        [
            "trip_id",
            "stop_sequence",
            "stop_id",
            "stop_name",
            "prev_arrival",
            "arrival",
            "stop_to_stop_minutes"
        ]
    ]
    .sort_values("stop_to_stop_minutes", ascending=False)
    .head(20)
)

,trip_id,stop_sequence,stop_id,stop_name,prev_arrival,arrival,stop_to_stop_minutes
82,01-ABY--10-T3-8630,11,22254,NaN,0 days 19:35:00,0 days 21:12:00,97.0
1462,01-ABY--23-T3-8630,11,22254,NaN,0 days 19:35:00,0 days 21:12:00,97.0
2398,01-ABY--8-T0-8630,11,22254,NaN,0 days 19:35:00,0 days 21:12:00,97.0
790,01-ABY--19-T0_WD08-8630,11,22254,NaN,0 days 19:35:00,0 days 21:12:00,97.0
562,01-ABY--18-T0_WD08-8630,11,22254,NaN,0 days 19:35:00,0 days 21:12:00,97.0
430,01-ABY--15-T3-8630,11,22254,NaN,0 days 19:35:00,0 days 21:12:00,97.0
778,01-ABY--18-T3-8630,11,22254,NaN,0 days 19:35:00,0 days 21:12:00,97.0
1702,01-ABY--25-T0_WD08-8630,11,22254,NaN,0 days 19:35:00,0 days 21:12:00,97.0
1990,01-ABY--2-T0-8630,11,22254,NaN,0 days 19:35:00,0 days 21:12:00,97.0
2206,01-ABY--5-T3-8630,11,22254,NaN,0 days 19:35:00,0 days 21:12:00,97.0
1234,01-ABY--21-T3-8630,11,22254,NaN,0 days 19:35:00,0 days 21:12:00,97.0
1078,01-ABY--20-T0-8630,11,22254,NaN,0 days 19:35:00,0 days 21:12:00,97.0
1246,01-ABY--22-T0_WD08-8630,11,22254,NaN,0 days 19:35:00,0 days 21:12:00,97.0
1690,01-ABY--24-T3-8630,11,22254,NaN,0 days 19:35:00,0 days 21:12:00,97.0
1474,01-ABY--24-T0_WD08-8630,11,22254,NaN,0 days 19:35:00,0 days 21:12:00,97.0
1918,01-ABY--25-T3-8630,11,22254,NaN,0 days 19:35:00,0 days 21:12:00,97.0
1006,01-ABY--19-T3-8630,11,22254,NaN,0 days 19:35:00,0 days 21:12:00,97.0
214,01-ABY--12-T0-8630,11,22254,NaN,0 days 19:35:00,0 days 21:12:00,97.0
38702,01-BGO--13-T0-8033,3,20301,NaN,0 days 17:00:00,0 days 18:13:00,73.0
48998,01-BGO--6-T0-8033,3,20301,NaN,0 days 17:00:00,0 days 18:13:00,73.0

In [31]:
# Check whether long-gap stop IDs exist in the stops dataset

long_gap_stop_ids = long_gaps["stop_id"].unique()

missing_stop_ids = [
    stop_id
    for stop_id in long_gap_stop_ids
    if stop_id not in stops["stop_id"].values
]

print("Long-gap stop IDs:", len(long_gap_stop_ids))
print("Missing from stops dataset:", len(missing_stop_ids))
print("Missing stop IDs:", missing_stop_ids)

Long-gap stop IDs: 19
Missing from stops dataset: 19
Missing stop IDs: [np.int64(20342), np.int64(22254), np.int64(20043), np.int64(20288), np.int64(20292), np.int64(20346), np.int64(20291), np.int64(22240), np.int64(20301), np.int64(20315), np.int64(20321), np.int64(20332), np.int64(20318), np.int64(20347), np.int64(22250), np.int64(20313), np.int64(20314), np.int64(20349), np.int64(20334)]

In [32]:
# Check the data types and compare stop IDs

print("stops stop_id type:", stops["stop_id"].dtype)
print("stop_times stop_id type:", stop_times["stop_id"].dtype)

print("\nExample stop IDs from stops:")
print(stops["stop_id"].head(20).tolist())

print("\nExample missing IDs from long gaps:")
print(missing_stop_ids)

stops stop_id type: object
stop_times stop_id type: int64

Example stop IDs from stops:
['11212', '11213', '11214', '11215', '11216', '11217', '11218', '12172', '12173', '12178', '12179', '12187', '12188', '12189', '12201', '12202', '12203', '12204', '12205', '12253']

Example missing IDs from long gaps:
[np.int64(20342), np.int64(22254), np.int64(20043), np.int64(20288), np.int64(20292), np.int64(20346), np.int64(20291), np.int64(22240), np.int64(20301), np.int64(20315), np.int64(20321), np.int64(20332), np.int64(20318), np.int64(20347), np.int64(22250), np.int64(20313), np.int64(20314), np.int64(20349), np.int64(20334)]

In [33]:
# Convert stop IDs to the same data type

stops["stop_id"] = stops["stop_id"].astype(str)
stop_times_sorted["stop_id"] = stop_times_sorted["stop_id"].astype(str)

# Recreate the long-gap dataframe
long_gaps = stop_times_sorted[
    stop_times_sorted["stop_to_stop_minutes"] > 30
].copy()

# Add stop names
stop_name_map = stops.set_index("stop_id")["stop_name"]
long_gaps["stop_name"] = long_gaps["stop_id"].map(stop_name_map)

# Display the longest gaps
display(
    long_gaps[
        [
            "trip_id",
            "stop_sequence",
            "stop_id",
            "stop_name",
            "prev_arrival",
            "arrival",
            "stop_to_stop_minutes"
        ]
    ]
    .sort_values("stop_to_stop_minutes", ascending=False)
    .head(20)
)

,trip_id,stop_sequence,stop_id,stop_name,prev_arrival,arrival,stop_to_stop_minutes
82,01-ABY--10-T3-8630,11,22254,Broadmeadows Station,0 days 19:35:00,0 days 21:12:00,97.0
1462,01-ABY--23-T3-8630,11,22254,Broadmeadows Station,0 days 19:35:00,0 days 21:12:00,97.0
2398,01-ABY--8-T0-8630,11,22254,Broadmeadows Station,0 days 19:35:00,0 days 21:12:00,97.0
790,01-ABY--19-T0_WD08-8630,11,22254,Broadmeadows Station,0 days 19:35:00,0 days 21:12:00,97.0
562,01-ABY--18-T0_WD08-8630,11,22254,Broadmeadows Station,0 days 19:35:00,0 days 21:12:00,97.0
430,01-ABY--15-T3-8630,11,22254,Broadmeadows Station,0 days 19:35:00,0 days 21:12:00,97.0
778,01-ABY--18-T3-8630,11,22254,Broadmeadows Station,0 days 19:35:00,0 days 21:12:00,97.0
1702,01-ABY--25-T0_WD08-8630,11,22254,Broadmeadows Station,0 days 19:35:00,0 days 21:12:00,97.0
1990,01-ABY--2-T0-8630,11,22254,Broadmeadows Station,0 days 19:35:00,0 days 21:12:00,97.0
2206,01-ABY--5-T3-8630,11,22254,Broadmeadows Station,0 days 19:35:00,0 days 21:12:00,97.0
1234,01-ABY--21-T3-8630,11,22254,Broadmeadows Station,0 days 19:35:00,0 days 21:12:00,97.0
1078,01-ABY--20-T0-8630,11,22254,Broadmeadows Station,0 days 19:35:00,0 days 21:12:00,97.0
1246,01-ABY--22-T0_WD08-8630,11,22254,Broadmeadows Station,0 days 19:35:00,0 days 21:12:00,97.0
1690,01-ABY--24-T3-8630,11,22254,Broadmeadows Station,0 days 19:35:00,0 days 21:12:00,97.0
1474,01-ABY--24-T0_WD08-8630,11,22254,Broadmeadows Station,0 days 19:35:00,0 days 21:12:00,97.0
1918,01-ABY--25-T3-8630,11,22254,Broadmeadows Station,0 days 19:35:00,0 days 21:12:00,97.0
1006,01-ABY--19-T3-8630,11,22254,Broadmeadows Station,0 days 19:35:00,0 days 21:12:00,97.0
214,01-ABY--12-T0-8630,11,22254,Broadmeadows Station,0 days 19:35:00,0 days 21:12:00,97.0
38702,01-BGO--13-T0-8033,3,20301,Castlemaine Station,0 days 17:00:00,0 days 18:13:00,73.0
48998,01-BGO--6-T0-8033,3,20301,Castlemaine Station,0 days 17:00:00,0 days 18:13:00,73.0

In [34]:
# Count long gaps by stop

long_gap_by_stop = (
    long_gaps
    .groupby(["stop_id", "stop_name"])["stop_to_stop_minutes"]
    .agg(["count", "mean", "max"])
    .sort_values("count", ascending=False)
)

display(long_gap_by_stop.head(20))

                                count       mean   max
stop_id stop_name
22240   Footscray Station         163  48.300613  55.0
20288   Ararat Station            160  31.000000  31.0
20314   Geelong Station           158  46.715190  52.0
22254   Broadmeadows Station      123  55.073171  97.0
20043   Southern Cross Station    120  33.325000  34.0
20342   Seymour Station           114  49.473684  53.0
20291   Bairnsdale Station        105  40.057143  41.0
20346   Stratford Station         105  38.580952  39.0
20318   Kerang Station             70  44.000000  44.0
20347   Swan Hill Station          70  47.042857  48.0
20315   Gisborne Station           66  34.575758  41.0
20292   Ballan Station             34  33.647059  35.0
20349   Terang Station             18  36.000000  36.0
20301   Castlemaine Station        17  73.000000  73.0
20313   Garfield Station           17  33.000000  33.0
20334   North Geelong Station      17  38.941176  40.0
22250   Dandenong Station          17  34.000000  34.0
20321   Lara Station               11  33.000000  33.0
20332   Nagambie Station            6  32.000000  32.0